### PR TITLE
 Issue #7 - Add Transparent Background Color to "Visit Gallery" Button

### PR DESCRIPTION
**Pull request by Thilagavathi1**
Issue #7 
This PR addresses an issue where the "Visit Gallery" button had an undesired background color. It introduces a transparent background color to enhance the button's appearance and align it with the project's design.

### CODE REVIEW

**Review by asyncdoggo — CHANGES_REQUESTED** [review]
Please avoid use of !important as much as possible, it is considered a bad practice, it must be used used sparingly and only when really necessary.
I'd suggest make changes to the parent element to fix the issue.

**Comment by Thilagavathi1** [comment]
@asyncdoggo Attaching here an screenshot for the fix.please check the pr and let me know if any issues
Screenshot 2023-10-13 at 4 43 14 PM

**Comment by asyncdoggo** [comment]
@Thilagavathi1 There is still the issue of the cursor-pointer property been given to the entire div that the button is in, instead of just the button.
I may have a fix for that but that will cause your changes to be obsolete unless you could fix that too.

**Comment by Thilagavathi1** [comment]
okay,let me work on this and update here.

**Comment by Thilagavathi1** [comment]
@asyncdoggo resolved the cursor issue.Please review it.

**Review by asyncdoggo — APPROVED** [review]

**Pull request merged**
